#!/usr/bin/env bash
# This script displays the content of /etc/passwd
# Shows only: username, user id, and home directory path
# Uses while loop to read the file

while IFS=: read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
