#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code
# Displays: OCCURRENCE_NUMBER IP HTTP_CODE
# Sorted from greatest to lowest number of occurrences

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -rn
``
